<div id="sidebar-confirm">
    <h3><?php echo $this->translate('Copy item'); ?></h3>
    <p><?php echo $this->translate('This process will not copy media. If you must copy media, you can use the <a href="https://omeka.org/s/modules/Osii/" target="_blank">Omeka S Item Importer</a> module.'); ?></p>
    <p><?php echo $this->translate('Are you sure you would like to copy this item?'); ?></p>
    <?php echo $this->form($form); ?>
</div>
<div class="resource-details">
    <h3><?php echo $resource->link($resource->displayTitle(), null, ['target' => '_blank']); ?></h3>
    <div><?php echo $this->escapeHtml($resource->displayDescription()); ?></div>
    <div class="meta-group">
        <h4><?php echo $this->translate('ID'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($resource->id()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Visibility'); ?></h4>
        <div class="value"><?php echo $resource->isPublic() ? $this->translate('Public') : $this->translate('Private'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Owner'); ?></h4>
        <div class="value">
        <?php
        $owner = $resource->owner();
        echo $owner
            ? $this->hyperlink($owner->name(), $this->url('admin/id', [
                'controller' => 'user',
                'action' => 'show',
                'id' => $owner->id(), ]
            )) : null;
            ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Created'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($this->i18n()->dateFormat($resource->created(), 'long')); ?></div>
    </div>
</div>
