<div id="sidebar-confirm">
    <h3><?php echo $this->translate('Copy item set'); ?></h3>
    <p><?php echo $this->translate('Are you sure you would like to copy this item set?'); ?></p>
    <?php echo $this->form($form); ?>
</div>
<div class="resource-details">
    <h3><?php echo $resource->link($resource->displayTitle(), null, ['target' => '_blank']); ?></h3>
    <div><?php echo $this->escapeHtml($resource->displayDescription()); ?></div>
</div>
